/**
 * bcrypt-password-hasher.test.js
 *
 * Verifies the worker-pool wrapper produces functionally identical
 * verify/hash behaviour to direct (in-thread) bcrypt for sample inputs.
 * In particular:
 *   - hashes generated by the worker pool verify against the same
 *     plaintext via direct bcrypt and vice-versa.
 *   - the worker-pool hasher rejects wrong passwords just like direct.
 *
 * The pool is torn down via `disposeBcryptWorkerPool()` in afterAll so the
 * Jest worker exits cleanly.
 */
import bcrypt from 'bcrypt';
import {
  BcryptPasswordHasher,
  disposeBcryptWorkerPool,
} from '../../infrastructure/crypto/bcrypt-password-hasher.js';
import { PasswordHash } from '../../domain/user/password-hash.js';

const ROUNDS = 4; // keep it cheap for tests

describe('BcryptPasswordHasher — worker-pool parity with direct bcrypt', () => {
  const direct = new BcryptPasswordHasher({ rounds: ROUNDS, useWorkerPool: false });
  const pooled = new BcryptPasswordHasher({ rounds: ROUNDS, useWorkerPool: true });

  afterAll(async () => {
    await disposeBcryptWorkerPool();
  });

  test('hash() returns a PasswordHash wrapping a valid bcrypt digest in both modes', async () => {
    const plaintext = 'parity-sample-pw-1';
    const fromDirect = await direct.hash(plaintext);
    const fromPooled = await pooled.hash(plaintext);
    expect(fromDirect).toBeInstanceOf(PasswordHash);
    expect(fromPooled).toBeInstanceOf(PasswordHash);
    // bcrypt prefixes look like "$2b$04$..." — sanity check both came out of bcrypt.
    expect(fromDirect.value).toMatch(/^\$2[abxy]\$/);
    expect(fromPooled.value).toMatch(/^\$2[abxy]\$/);
  });

  test('verify() succeeds cross-mode (pooled hashes verify under direct, and vice-versa)', async () => {
    const plaintext = 'parity-sample-pw-2';
    const pooledHash = await pooled.hash(plaintext);
    const directHash = await direct.hash(plaintext);

    // Pooled-produced hash verifies under direct verify.
    await expect(direct.verify(plaintext, pooledHash)).resolves.toBe(true);
    // Direct-produced hash verifies under pooled verify.
    await expect(pooled.verify(plaintext, directHash)).resolves.toBe(true);

    // And both reject the wrong password.
    await expect(direct.verify('wrong', pooledHash)).resolves.toBe(false);
    await expect(pooled.verify('wrong', directHash)).resolves.toBe(false);
  });

  test('multiple parallel worker-pool calls all complete successfully', async () => {
    const plaintexts = Array.from({ length: 8 }, (_, i) => `parallel-pw-${i}`);
    const hashes = await Promise.all(plaintexts.map((p) => pooled.hash(p)));
    const verifications = await Promise.all(
      hashes.map((h, i) => pooled.verify(plaintexts[i], h)),
    );
    expect(verifications.every((v) => v === true)).toBe(true);
  });

  test('rejects empty plaintext on hash and returns false on verify', async () => {
    await expect(pooled.hash('')).rejects.toThrow();
    const h = await pooled.hash('non-empty');
    await expect(pooled.verify('', h)).resolves.toBe(false);
  });

  test('hash produced by either mode is a valid bcrypt hash directly verifiable by the bcrypt module', async () => {
    const plaintext = 'parity-direct-verify';
    const pooledHash = await pooled.hash(plaintext);
    const ok = await bcrypt.compare(plaintext, pooledHash.value);
    expect(ok).toBe(true);
  });
});
