-- =====================================================
-- 002 — performance optimisation migration  (NO-OP since 2026-10)
-- =====================================================
--
-- This migration used to `\i`-include ~6,500 lines of tuning, monitoring,
-- caching and benchmarking SQL from database/{optimizations,monitoring,
-- cache,benchmarks}/. When the contract suites were first run against a
-- real Postgres (SOTA loop 13) it turned out that file set had **never
-- applied successfully on any database**:
--
--   * indexes on non-existent columns (`workflows.failed_at`)
--   * catalog views using `tablename`/`indexname` instead of
--     `relname`/`indexrelname`; references to `pg_stat_user_matviews`
--   * `round(double precision, int)` (needs ::numeric), non-IMMUTABLE
--     partial-index predicates, invalid PL/pgSQL (`RETURN NEXT x` with OUT
--     params, unterminated strings, stray `END`), enum literal 'unknown'
--   * hard dependency on pg_stat_statements via shared_preload_libraries
--   * dozens of cascading "relation does not exist" errors
--
-- In addition, the production runner (migrate.js) executes each file in
-- one transaction, which `CREATE INDEX CONCURRENTLY` forbids, and cannot
-- process psql `\i` includes — so this migration aborted every fresh
-- `npm run db:migrate`.
--
-- No application code references any object those scripts create
-- (verified: 0 of 124 object names appear under src/backend), so no
-- deployed environment can depend on them. The scripts are kept as an
-- opt-in DBA toolkit under database/ (run individually with psql after
-- fixing); they are no longer part of the schema migration chain.
--
-- Keeping this file (rather than deleting it) preserves migration
-- numbering and the runner's bookkeeping for any environment that
-- recorded a failed attempt.

SELECT 1;
